"""
Regenerate the cross-language observation parity fixture.

The 3D environment is implemented twice: here in Python (what the agent
trains against) and in Rust at duct_rl/web/crate/src/grid3d.rs (what it plays
back against in the browser). If the two drift, a trained policy silently
behaves differently on playback than it did in training.

This script walks a few fixed action sequences and records the observation
after every step. Both test suites replay those sequences and compare against
the recorded values, so a change to either implementation that isn't mirrored
in the other turns into a failing test.

Python is the source of truth here — it is the side the agent trains against.

Usage:
    python gen_obs_parity.py
"""

from __future__ import annotations

import json
from pathlib import Path

from grid3d import OBS_DIM, build_scene, compute_obs, reset, step
from mep_config import MEP_SYSTEMS
from rooms3d import get_room_3d

OUTPUT = Path(__file__).resolve().parent.parent / "testdata" / "obs_parity.json"

# Each sequence is chosen to exercise the parts of the observation that depend
# on episode history, not just position.
SCENARIOS = [
    {
        # Straight runs, turns, vertical moves, and backtracking onto
        # already-visited voxels.
        "room": "simple",
        "mep": "duct",
        "actions": [0, 0, 0, 2, 2, 4, 4, 1, 1, 5, 3, 0, 0, 2],
    },
    {
        # pipe has min_straight_before_bend=2, so the early turns here get
        # rejected — the bend flag and straight_run must track that.
        "room": "corridor",
        "mep": "pipe",
        "actions": [0, 2, 0, 0, 2, 2, 4, 4, 1, 5, 3, 3],
    },
    {
        # Vertical shaft hunting, plus collisions with the floor slab.
        "room": "multi_floor",
        "mep": "cable_tray",
        "actions": [4, 4, 4, 4, 0, 0, 2, 2, 4, 4, 5, 1],
    },
]


def build_fixture() -> dict:
    scenarios = []
    for spec in SCENARIOS:
        scene = build_scene(get_room_3d(spec["room"]), MEP_SYSTEMS[spec["mep"]])
        mep = MEP_SYSTEMS[spec["mep"]]
        state = reset(scene)

        # Index 0 is the observation at reset; index i+1 follows actions[i].
        observations = [compute_obs(scene, state, mep).tolist()]
        for action in spec["actions"]:
            result = step(scene, state, action, mep)
            state = result.state
            observations.append(compute_obs(scene, state, mep).tolist())
            assert not result.done, (
                f"scenario {spec['room']}/{spec['mep']} ended early; "
                "pick a shorter action sequence"
            )

        scenarios.append({**spec, "obs": observations})

    return {
        "_comment": (
            "Generated by duct_rl/python/gen_obs_parity.py. Both the Python "
            "and Rust test suites replay these action sequences and compare "
            "observations, so the two implementations cannot drift silently."
        ),
        "obs_dim": OBS_DIM,
        "scenarios": scenarios,
    }


if __name__ == "__main__":
    fixture = build_fixture()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        json.dump(fixture, f, indent=1)
        f.write("\n")
    steps = sum(len(s["actions"]) for s in fixture["scenarios"])
    print(f"Wrote {OUTPUT}")
    print(f"  {len(fixture['scenarios'])} scenarios, {steps} steps, "
          f"obs_dim={fixture['obs_dim']}")
